name: CI Workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Generate Sitemap & Robots Files
        run: npm run postbuild

      - name: Push to Hostinger
        run: |
          git remote add hostinger git@github.com:RjTravelHelpline/Jaipur-Taxi-Service.git
          git push hostinger master
