name: Build, Test & Deployment Workflow

on:
  push:
    branches:
      - master
      - '**' # Runs for all branches (optional)
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build
        continue-on-error: true

      - name: Post Build for Sitemap & Robots
        run: |
          npm run postbuild
          git config --global user.email "yj606089@gmail.com"
          git config --global user.name "RjTravelHelpline"
          git add public/sitemap.xml public/robots.txt
          git commit -m "Add generated sitemap.xml and robots.txt"
          git push https://${{ secrets.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 }}@github.com/RjTravelHelpline/Jaipur-Taxi-Service.git
        env:
          GH_TOKEN: ${{ secrets.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 }}

      - name: List Generated Files
        run: ls -la

      - name: Notify Success
        if: success()
        run: echo "Build successful! Ready to merge."

      - name: Notify Failure
        if: failure()
        run: echo "Build failed. Please fix errors before merging."
