name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - master # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Adjust Node.js version as needed

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Build the project
      - name: Run build command
        run: |
          npm run build

      # Step: Verify the build output
      - name: Verify build output
        run: |
          if [ ! -d "./out" ]; then
            echo "Error: Build directory 'out' does not exist."
            exit 1
          fi

      # Step 5: Deploy only the `out` directory to deploy branch
      - name: Deploy only the `out` directory to deploy branch
        run: |
          # Make sure we're in a valid Git repository and on the correct branch
          git status

          # Configure Git user for commits
          git config user.name "RjTravelHelpline"
          git config user.email "yj606089@gmail.com"

          # Ensure the 'deploy' branch exists and is checked out
          git checkout --orphan deploy

          # Remove all files and directories except 'out'
          find . -mindepth 1 -not -path './out*' -exec rm -rf {} + || echo "Some files were not found and could not be deleted"

          # Check if the 'out' directory exists and copy its contents
          if [ -d "./out" ]; then
            echo "Copying contents of 'out' directory..."
            cp -R ./out/* .
            rm -rf out  # Clean up 'out' directory after copying
          else
            echo "'out' directory not found. Please make sure it's built before deployment."
            exit 1
          fi

          # Commit and push changes to the 'deploy' branch
          git add .
          git commit -m "Update deployed build" || echo "No changes to commit"
          git push origin deploy --force
