name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up SSH key
      - name: Set up SSH key for connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Build your project (adjust this according to your build process)
      - name: Build Project
        run: npm run build

      # Deploy to Hostinger
      - name: Deploy to Hostinger
        run: |
          ssh -o StrictHostKeyChecking=no -p 65002 u525176569@217.21.94.56 << 'EOF'
            cd domains
            cd taxirentaljaipur.com
            cd public_html
            rm -rf *
            cp -r /path/to/your/build/* .
          EOF
